apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-cluster-master-opensearch-cluster-master-0
  namespace: pega
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-cluster-master-opensearch-cluster-master-1
  namespace: pega
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-cluster-master-opensearch-cluster-master-2
  namespace: pega
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp3
  volumeMode: Filesystem
